adding the project in the branch for the mull request
Marwen-Brini/project1 pull request #1
Opened 2021-02-16 08:34 UTC by Marwen-Brini

adding the project files

2021-02-16 08:45 UTC, descholar-ceo requested changes
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @Marwen-Brini   :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this project. However your code review request is marked as invalid due to the following reasons:

1. Your repository does not have descriptive readme file
2. This pull request does not not have an appropriate description
=>Add a readme file which follow microvrse readme template. Refer to [this one](https://github.com/microverseinc/readme-template)
=> Add an appropriate description to this PR, talk about the tasks that you have completed on branch
Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-02-16 09:08 UTC, Marwen-Brini commented
@descholar-ceo: i've done the changes, is it compatible now?

2021-02-16 10:30 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Marwen-Brini  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone almost looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement carefully the minimum requirements of this project, keep it up, and your project is really almost done.
:+1: I liked the way you write paths, that is a best practice keep it up :muscle:
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The license, and issues links from the readme file are broken, fix them.
- [ ] Add a live demo link in readme file
- [ ] On the `The Theory of Inflation` section, the images are overlapping some texts. Please take care of that 

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2021-02-16 12-22-05](https://user-images.githubusercontent.com/56886064/108049957-a3574700-7051-11eb-99e0-5d8dc8401d64.png)| ![Screenshot from 2021-02-16 12-23-22](https://user-images.githubusercontent.com/56886064/108050049-caae1400-7051-11eb-8fda-3bf36fa2e90f.png) |

:point_right: Could you see the difference :question: :question: :question: 

- [x] Complete the text which is between the `The Theory of Inflation` title and the image
- [x] Social media icons should be aligned on a row, fix them

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2021-02-16 12-25-55](https://user-images.githubusercontent.com/56886064/108050327-24164300-7052-11eb-9c49-0e5bc0c84742.png) | ![Screenshot from 2021-02-16 12-26-28](https://user-images.githubusercontent.com/56886064/108050401-37291300-7052-11eb-800f-07746ab598af.png) |

:point_right: Could you see the difference :question: :question: :question: 

- [x] Below the title, you missed the social media icons

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2021-02-16 12-27-34](https://user-images.githubusercontent.com/56886064/108050510-5e7fe000-7052-11eb-8fab-10d1f8095305.png) | ![Screenshot from 2021-02-16 12-28-08](https://user-images.githubusercontent.com/56886064/108050571-722b4680-7052-11eb-82c2-ad91bcfe4f55.png) |

:point_right: Could you see the difference :question: :question: :question: 

- [x] You are missing the navigation bar, please add it
- [x] In your clone, you are missing some blue colors for the links, whereas in the original page there are. Please fix that up!
- [x] Remember to make titles and subtitles in bold as they are in the original page
- [ ] The right side `Edit's pick` is missing the title, kindly add it
- [ ] The boxes which are in `Suggested newsletters for you`, have hover effect, when you hover a box, the circled plus button get changed, make sure that you implement that behaviour
- [ ] Make sure that the bottom part of the main content looks like the original page, the leftmost side content is overlapping the rightmost side content
- [ ] Generally speaking: most of the sections in your clone, don't have titles, please review your clone carefully comparing it with the original page, and add them.
- [ ] The logo in upper footer, is stretched, fix it up
- [ ] The subscribe section in the footer: make sure that the four first links are bold, and bit bigger than the rest of the links, and also make sure that section has a left border
- [ ] You are missing linters config on this branch. Please refer to [this link](https://github.com/microverseinc/linters-config/tree/master/html-css) and make sure that you configure linters before submitting another code review request

Codes
========
- [ ] Try to use sementic HTML tags: `<header>; <nav>; <main>; <footer>; <article>; <section>; <aside>`
- [ ] Try to use `flex`, `grid`, `float` for alignment of the elements, so that way you will be practicing how to use those techniques. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from the pathwright

- [ ] Implement all changes I suggested in inline comments in your codes

# [Optional changes] :yellow_circle: 
- [ ] It would be very nice if you add a screeshoot in the readme file
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-02-16 10:30 UTC, descholar-ceo commented on app.css
> +	padding: 0 !important;
[required] Remove all of `!improtant` => this is a bad practice for CSS because it makes your codes difficult to maintain

2021-02-16 10:30 UTC, descholar-ceo commented on app.css
> +	position: absolute;
[required] You are repeating this particular property several times `position: absolute;` => CSS codes need to be DRY (don't repeat yourself). 

_Note:_ Inspect your CSS file carefully and refactory it in the following way:

### :point_right:  Whenever you see some properties are repeating themselves several times as this example, please create utility classes for them and put those properties in those classes, so that you will be able to re-ue those classes on the elements which need them

2021-02-17 08:36 UTC, Marwen-Brini commented
@descholar-ceo  i've done the changes let me know if i missed anything and thank you

2021-02-18 15:39 UTC, Marwen-Brini commented
@descholar-ceo i've added few other missing items ,let me know if i missed something

2021-02-18 18:08 UTC, Temmarie requested changes
## Changes Required! :recycle:

### Hi @Marwen-Brini     ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.

---

### **Recommended**

**General**

- [x] I see you have a different font family andd size from that in the actual [NYT](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0) site. Use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension to solve this issue.

**Section Specific**
- [x] Navigation bar
- The navbar elements to the left( the hamburger button, space &cosmos) are a lot bigger than that of the actual site, and the search button is smaller.
- The nav links and buttons are tilting to the right. Please evenly distribute the space.

**Original** |  **Your clone**
------------ | -------------
![Screenshot (73)](https://user-images.githubusercontent.com/49621279/108278551-0f0fe180-7130-11eb-9a6d-374388c02c54.png) | ![Screenshot (81)](https://user-images.githubusercontent.com/49621279/108399439-f60a3d80-71ce-11eb-9c30-ea34e80467f2.png)

- [ ] Main Content
- The social media icons should be in a row, please fix it.

**Original** |  **Your clone**
------------ | -------------
 ![Screenshot (85)](https://user-images.githubusercontent.com/49621279/108401374-1e933700-71d1-11eb-9e68-317490bca2d8.png) | ![Screenshot (82)](https://user-images.githubusercontent.com/49621279/108400210-cf003b80-71cf-11eb-8831-5709daa27ba7.png)

- The `Suggested Newsletters` and `Most Popular` sections are bleeding into each other.

**Original** |  **Your clone**
------------ | -------------                
![Screenshot (83)](https://user-images.githubusercontent.com/49621279/108400629-4635cf80-71d0-11eb-9c5e-e532b95f5535.png) | ![image](https://user-images.githubusercontent.com/49621279/108400938-a3ca1c00-71d0-11eb-8a01-1524fea48703.png)


 
- The `More in Space and Anatomy` section has some texts bleeding into themselves, please fix this.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-02-19 14:56 UTC, mimipeshy commented
### STATUS :APPROVED :partying_face: :champagne: 

Hey team @Marwen-Brini, you have done an amazing job with the feedback given. Your page looks almost similar to the original page. This project is therefore approved. Go ahead and merge

All the best in the next projects. Happy Coding :computer: 

Regards
Peris Ndanu

2021-02-19 14:59 UTC, merged